import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import SidebarComponent from "./side-bar";
import { getSession } from "@/lib/auth";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();
	return (
		<html lang="en">
			<body className={inter.className}>
				<div
					className={cn(
						"rounded-md flex flex-col md:flex-row bg-gray-100 w-full flex-1 mx-auto border border-neutral-200 overflow-hidden",
						"h-screen"
					)}
				>
					<SidebarComponent session={session} />
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	);
}
